MANUAL = {
    "commands":
        "```markdown\n"
        "For the information on the arguments of each command, please consult\n"
        "the manual for each specific command instead.\n"
        "\n"
        "# Bot information\n"
        "- author\n"
        "- purpose\n"
        "- privacy\n"
        "- help\n"
        "- man\n"
        "- link\n"
        "\n"
        "# User commands\n"
        "- register\n"
        "- unregister\n"
        "- forgot_code\n"
        "\n"
        "# Data Retrieval\n"
        "- servers\n"
        "- day\n"
        "- week\n"
        "- period\n"
        "- matches\n"
        "- results\n"
        "- character\n"
        "- strategy\n"
        "- build\n"
        "\n"
        "# Utilities\n"
        "- random\n"
        "```",
    # Data Retrieval
    "day": (
        "day",
        [("date", "Date to build overview for", True, "today")],
        "Display the amount of matches registered for each server on "
        "any given day in a table format."
    ),
    "week": (
        "week",
        [],
        "Display the amount of matches registered for each server for the "
        "last seven days in a table format."
    ),
    "period": (
        "period",
        [("start", "Start date of the period", False, None),
         ("end", "End date of the period", True, "today")],
        "Display the amount of matches registered for each server in a "
        "given period in a table format."
    ),
    "servers": (
        "servers",
        [],
        "Display the known SWTOR servers and their current status."
    ),
    "matches": (
        "matches",
        [("server", "Three-letter server code", False, None),
         ("date", "Date of the day to display matches for", True, "today")],
        "Display the matches registered on a given server in a table "
        "format with additional information, including the start and "
        "end time, match type, map type and end score if available."
    ),
    "results": (
        "results",
        [("server", "Three-letter server code"), False, None,
         ("date", "Date of the match", False, None),
         ("start", "Start time of the match", False, None)],
        "Display the registered results of a specific match in a table "
        "format, including damage dealt, damage taken and other "
        "statistics. Only displays results that have been shared through "
        "the GSF Parser."
    ),
    "character": (
        "character",
        [("server", "Three-letter server code", False, None),
         ("name", "Name of the character to lookup", False, None)],
        "Display the Discord tag of the owner of a certain character on "
        "a given server. This is only possible if the owner has chosen "
        "to share this information."
    ),
    # Bot Information
    "author":
        "```markdown\n"
        "Command: author\n"
        "Arguments: None\n"
        "\n"
        "Display the copyright and license information, including information\n"
        "on the usage of data generated by this bot.\n"
        "```",
    "purpose":
        "```markdown\n"
        "Command: purpose\n"
        "Arguments: None\n"
        "\n"
        "Display a text explaining the purpose of this bot.\n"
        "```",
    "privacy":
        "```markdown\n"
        "Command: privacy\n"
        "Arguments: None\n"
        "\n"
        "Display a text explaining what data is collected and how it is\n"
        "stored.\n"
        "```",
    "man":
        "```markdown\n"
        "Command: man\n"
        "Arguments:\n"
        "- command, optional, assumes `commands` if not given.\n"
        "\n"
        "Displays a text explaining how to use the different bot commands.\n"
        "```",
    "link":
        "```markdown\n"
        "Command: link\n"
        "Arguments: None\n"
        "\n"
        "Displays download links for the latest version of the GSF Parser.\n"
        "```",
    "help":
        "```markdown\n"
        "Command: help\n"
        "Arguments: None\n"
        "\n"
        "Displays a basic help text.\n"
        "```",
    # User commands
    "register":
        "```markdown\n"
        "Command: register\n"
        "Arguments: None\n"
        "\n"
        "Register yourself as a user of this bot. A security key is sent to \n"
        "you via PM.\n"
        "```",
    "unregister":
        "```markdown\n"
        "Command: unregister\n"
        "Arguments: None\n"
        "\n"
        "Unregister yourself as a user of this bot. Permanently and\n"
        "irreversibly removes all of your personal data from the database.\n"
        "This command is **irreversible** and takes effect **immediately, all\n"
        "your data is **instantly** removed.\n"
        "```",
    "forgot_code":
        "```markdown\n"
        "Command: forgot_code\n"
        "Arguments: None\n"
        "\n"
        "Request a new security key for accessing the Discord Bot Server. Your\n"
        "old code is invalidated instantly and only the new code can be used.\n"
        "```",
    "scoreboard":
        "```markdown\n"
        "Command: scoreboard\n"
        "Arguments:\n"
        "- type, optional, table assumed if not given\n"
        "  Possible values:\n"
        "  - table, output sent as a table\n"
        "  - excel, output sent as an Excel file\n"
        "  - csv, output sent as a CSV file\n"
        "\n"
        "Performs cropping and OCR on a screenshot of a scoreboard in order to\n"
        "build a table with the results. The screenshot should be sent as an\n"
        "attachment.\n"
        "```",
    # Utilities
    "random":
        "```markdown\n"
        "Command: random\n"
        "Arguments:\n"
        "- type, optional\n"
        "\n"
        "Choose a random ship type out of the possibilities. The result is sent\n"
        "as a Tier-Type combination. You can specify the type by using the type\n"
        "argument:\n"
        "  Fighter\n"
        "  Gunship\n"
        "  Scout\n"
        "  Bomber\n"
        "```",
    "build":
        "```markdown\n"
        "Command: build\n"
        "Arguments:\n"
        "- command: create, delete, select, search, show, stats, lookup, ttk\n"
        "- additional arguments for each specific command\n"
        "\n"
        "This command is used to manipulate the build calculator. Use the\n"
        "build calculator to design builds and share them and view the\n"
        "statistics of a build. All build data is up-to-date with nuGSF.\n"
        "\n"
        "Each command requires its own arguments. Check the manuals of\n"
        "build_commands for more information on each individual command.\n"
        "\n"
        "Use the manual of build_global for general information.\n"
        "```",
    "build_global":
        "```markdown\n"
        "# Global build calculator definitions\n"
        "- ship identifier: The common way of referring to a ship is by\n"
        "     tier string. This bot requires a similar format that also\n"
        "     specifies faction. Examples:\n"
        "     I2F: Imperial Tier 2 Strike Fighter - Quell\n"
        "     R1S: Republic Tier 1 Scout - NovaDive\n"
        "     R3G: Republic Tier 3 Gunship - Comet Breaker\n"
        "- component path: To refer to components and crew members, this\n"
        "     build calculator uses a path-style format.\n\n"
        "     For components, the format is:\n\n"
        "       category/component_identifier/upgrade_string.\n\n"
        "     The component identifiers are very flexible. You can use either\n"
        "     the first part of the name, a unique part of the first part of\n"
        "     the name, or a unique alias of a component, which correspond to\n"
        "     widely used names of the components.\n\n"
        "     Examples:\n"
        "     sw/clusters/123RL - SecondaryWeapon, Cluster Missiles\n"
        "     pw/heavy/123RL - PrimaryWeapon, Heavy Laser Cannon\n"
        "     primary/bursts/12 - PrimaryWeapon, Burst Laser Cannon\n"
        "     sp/ov/12L - Shields (ShieldProjector), Overcharged Shield\n\n"
        "     Crew member paths are a little different. They are in the format\n\n"
        "       crew/crew_role/name_identifier\n\n"
        "     Again, many identifiers are supported.\n\n"
        "     Examples:\n"
        "     crew/engineering/blizz - Engineering, Blizz (Imperial)\n"
        "     crew/d/bro - Defensive, Broonmark (Republic)\n"
        "```",
    "build_commands":
        "```markdown\n"
        "# Subcommands:\n"
        "- create: Create a new build in the build calculator\n"
        "    Arguments: ship identifier, name (in quotes!), public (optional)\n"
        "- select: Select a new component or crew member for a ship\n"
        "    Arguments: Build ID number, crew path or component path\n"
        "- lookup: Lookup the ID number of a build or the details of a\n"
        "    component or crew member.\n"
        "    Arguments:\n"
        "    - For Build ID number lookup: Ship name (in quotes!)\n"
        "    - For crew member details: A crew path without the role\n"
        "    - For component details: A component path\n"
        "- delete: Delete a build from the build calculator\n"
        "    Arguments: Build ID number\n"
        "    *Warning*: This action is immediate and irreversible\n"
        "- stats: Show the statistics for a specific build (PM-only)\n"
        "- show: Show an overview of components and crew for a build\n"
        "- search: Search for public builds with certain criteria. See\n"
        "    the manual of build_search for more information.\n"
        "- ttk: Calculate the Time-To-Kill of one build against another.\n"
        "```",
    "strategy":
        "```markdown\n"
        "# Strategy Manager Companion for GSF Parser\n"
        "Command: strategy\n"
        "The GSF Parser allows users to upload their strategies to the\n"
        "Discord Bot to be used with this command. All strategies are\n"
        "private and can only be manipulated by the owner.\n"
        "\n"
        "# Subcommands\n"
        "- list: List all the strategies uploaded\n"
        "- show {strategy}: Show the phase names and map type for an\n"
        "      uploaded strategy owned by you\n"
        "- render {strategy} {phase}: Render a phase of a strategy to\n"
        "      an image and upload it in a rich embed with the text\n"
        "      description of the phase.\n"
        "- delete {strategy}: Delete a strategy from the database\n"
        "```"
}
