MANUAL = {
    "commands":
        "```markdown\n"
        "For the information on the arguments of each command, please consult\n"
        "the manual for each specific command instead.\n"
        "\n"
        "# Bot information\n"
        "- author\n"
        "- purpose\n"
        "- privacy\n"
        "- help\n"
        "- man\n"
        "- link\n"
        "\n"
        "# User commands\n"
        "- register\n"
        "- unregister\n"
        "- forgot_code\n"
        "\n"
        "# Data Retrieval\n"
        "- servers\n"
        "- day\n"
        "- week\n"
        "- period\n"
        "- matches\n"
        "- results\n"
        "- character\n"
        "- strategy\n"
        "- build\n"
        "\n"
        "# Utilities\n"
        "- random\n"
        "```",
    # Data Retrieval
    "day": (
        "day",
        [("date", "Date to build overview for", True, "today")],
        "Display the amount of matches registered for each server on "
        "any given day in a table format."
    ),
    "week": (
        "week",
        [],
        "Display the amount of matches registered for each server for the "
        "last seven days in a table format."
    ),
    "period": (
        "period",
        [("start", "Start date of the period", False, None),
         ("end", "End date of the period", True, "today")],
        "Display the amount of matches registered for each server in a "
        "given period in a table format."
    ),
    "servers": (
        "servers",
        [],
        "Display the known SWTOR servers and their current status."
    ),
    "matches": (
        "matches",
        [("server", "Two-letter server code", False, None),
         ("date", "Date of the day to display matches for", True, "today")],
        "Display the matches registered on a given server in a table "
        "format with additional information, including the start and "
        "end time, match type, map type and end score if available."
    ),
    "results": (
        "results",
        [("server", "Two-letter server code", False, None),
         ("date", "Date of the match", False, None),
         ("start", "Start time of the match", False, None)],
        "Display the registered results of a specific match in a table "
        "format, including damage dealt, damage taken and other "
        "statistics. Only displays results that have been shared through "
        "the GSF Parser."
    ),
    "character": (
        "character",
        [("server", "Two-letter server code", False, None),
         ("name", "Name of the character to lookup", False, None)],
        "Display the Discord tag of the owner of a certain character on "
        "a given server. This is only possible if the owner has chosen "
        "to share this information."
    ),
    # Bot Information
    "author": (
        "author",
        [],
        "Display the copyright and license information, including "
        "information on the usage of data generated by this bot."
    ),
    "purpose": (
        "purpose", [], "Display a text explaining the purpose of this bot."

    ),
    "privacy": (
        "privacy", [],
        "Display a text explaining what data is collected and how it is stored.",
    ),
    "man": (
        "man",
        [("command", "Command to display manual for", True, "commands")]
    ),
    "link": (
        "link", [], "Build download links for the latest GSF Parser."
    ),
    "help": ("help", [], "Display a basic help text."),
    "setup": (
        "setup",
        [],
        "Display a text with more information on how to get started "
        "using this bot."
    ),
    # User commands
    "register": (
        "register",
        [],
        "Register yourself to use the bot. A security key to enter into "
        "the GSF Parser is sent to you through PM."
    ),
    "unregister": (
        "unregister",
        [],
        "Remove your registration with the bot. *Immediately* and "
        "*irrevocably* erases *all* your data from the database."
    ),
    "forgot_code": (
        "forgot_code",
        [],
        "Generate a new authentication code to use with the GSF Parser "
        "Discord Bot Server. Your old code is invalidated and only your "
        "new code can be used."
    ),
    "scoreboard": (
        "scoreboard",
        [("image", "Attach an image of the scoreboard you would like to "
                   "parse to the message containing your command.",
          False, None),
         ("type", "Output type you would like to have the results of "
                  "the parsing in. You can choose from:\n"
                  "- table, output sent as a table in a code block\n"
                  "- excel, output attached as an Excel file\n"
                  "- csv, output attached as a CSV file\n",
          True, "table")]
    ),
    # Utilities
    "random": (
        "random",
        [("type", "Ship type you want a random choice from", True, "Any")],
        "Choose a random ship out of all the available ships. Argument "
        "`type` limits the choices to a single ship type (`Fighter`, "
        "`Gunship`, `Scout` or `Bomber`)."
    ),
    "build": (
        "build",
        ["varargs", "Variable amount of arguments", False, None],
        "This command is used to manipulate the build calculator. Use "
        "the build calculator to design and share builds as well as "
        "view the statistics of a build. All build data is up-to-date "
        "with nuGSF.\n\n"
        "Each subcommand requires its own arguments. Check the manuals "
        "of each of the subcommands by using `man \"build {command}\"."
        "Use the manual of `build_global` for more information."
    ),
    "build_global":
        "```markdown\n"
        "# Global build calculator definitions\n"
        "- ship identifier: The common way of referring to a ship is by\n"
        "     tier string. This bot requires a similar format that also\n"
        "     specifies faction. Examples:\n"
        "     I2F: Imperial Tier 2 Strike Fighter - Quell\n"
        "     R1S: Republic Tier 1 Scout - NovaDive\n"
        "     R3G: Republic Tier 3 Gunship - Comet Breaker\n"
        "- component path: To refer to components and crew members, this\n"
        "     build calculator uses a path-style format.\n\n"
        "     For components, the format is:\n\n"
        "       category/component_identifier/upgrade_string.\n\n"
        "     The component identifiers are very flexible. You can use either\n"
        "     the first part of the name, a unique part of the first part of\n"
        "     the name, or a unique alias of a component, which correspond to\n"
        "     widely used names of the components.\n\n"
        "     Examples:\n"
        "     sw/clusters/123RL - SecondaryWeapon, Cluster Missiles\n"
        "     pw/heavy/123RL - PrimaryWeapon, Heavy Laser Cannon\n"
        "     primary/bursts/12 - PrimaryWeapon, Burst Laser Cannon\n"
        "     sp/ov/12L - Shields (ShieldProjector), Overcharged Shield\n\n"
        "     Crew member paths are a little different. They are in the format\n\n"
        "       crew/crew_role/name_identifier\n\n"
        "     Again, many identifiers are supported.\n\n"
        "     Examples:\n"
        "     crew/engineering/blizz - Engineering, Blizz (Imperial)\n"
        "     crew/d/bro - Defensive, Broonmark (Republic)\n"
        "```",
    "build_commands":
        "```markdown\n"
        "# Subcommands:\n"
        "- create: Create a new build in the build calculator\n"
        "    Arguments: ship identifier, name (in quotes!), public (optional)\n"
        "- select: Select a new component or crew member for a ship\n"
        "    Arguments: Build ID number, crew path or component path\n"
        "- lookup: Lookup the ID number of a build or the details of a\n"
        "    component or crew member.\n"
        "    Arguments:\n"
        "    - For Build ID number lookup: Ship name (in quotes!)\n"
        "    - For crew member details: A crew path without the role\n"
        "    - For component details: A component path\n"
        "- delete: Delete a build from the build calculator\n"
        "    Arguments: Build ID number\n"
        "    *Warning*: This action is immediate and irreversible\n"
        "- stats: Show the statistics for a specific build (PM-only)\n"
        "- show: Show an overview of components and crew for a build\n"
        "- search: Search for public builds with certain criteria. See\n"
        "    the manual of build_search for more information.\n"
        "- ttk: Calculate the Time-To-Kill of one build against another.\n"
        "```",
    "build create": (
        "build create",
        [("base", "Base ship identifier, see `man build_global`", False, None),
         ("name", "Name of the new build, enclosed by quotes", False, None),
         ("public", "Flag to allow others to view the build", True, "")],
        "Create a new build in the build database of the Bot. The build "
        "is based on teh ship which is specified using `base`."
    ),
    "build select": (
        "build select",
        [("build", "ID number of build to manipulate", False, None),
         ("path", "Valid component or crew path to set", False, None)],
        "Update one of the components or crew members in the build "
        "specified. See `man build_global` for more information on "
        "build paths."
    ),
    "build lookup": (
        "build lookup",
        [("path", "Component or crew member path to look up", False, None)],
        "Show the details of a specific component or crew member in a "
        "rich embed format."
    ),
    "build delete": (
        "build delete",
        [("build", "ID number of build to delete", False, None)],
        "Delete a build that is owned by you from the database. "
        "Deletion is immediate and cannot be undone."
    ),
    "build stats": (
        "build stats",
        [("build", "ID number of build to show stats for", False, None)],
        "Show a list of numerical statistics of a build."
    ),
    "build show": (
        "build show",
        [("build", "ID number of build to show", False, None)],
        "Show the components and creww members selected in a build in "
        "a rich embed format."
    ),
    "build search": (
        "build search",
        [("*paths", "Build paths as search requirements, separated by `;`",
            False, None)],
        "Search for public builds with specific criteria. Upgrades in "
        "component paths are disregarded when searching."
    ),
    "build ttk": (
        "build ttk",
        [("source", "ID number of build that is the one doing the shooting", False, None),
         ("target", "ID number of build that is the victim", False, None)],
        "Perform a Time-To-Kill calculation based upon the damage dealt "
        "by the PrimaryWeapon of the source build onto the target build. "
        "Shield piercing and other statistics are accounted for. Can "
        "only be performed on builds owned by you or builds that are "
        "public.\n"
        "**Note**: Evasion is not considered in the calculation."
    ),
    "strategy":
        "```markdown\n"
        "# Strategy Manager Companion for GSF Parser\n"
        "Command: strategy\n"
        "The GSF Parser allows users to upload their strategies to the\n"
        "Discord Bot to be used with this command. All strategies are\n"
        "private and can only be manipulated by the owner.\n"
        "\n"
        "# Subcommands\n"
        "- list: List all the strategies uploaded\n"
        "- show {strategy}: Show the phase names and map type for an\n"
        "      uploaded strategy owned by you\n"
        "- render {strategy} {phase}: Render a phase of a strategy to\n"
        "      an image and upload it in a rich embed with the text\n"
        "      description of the phase.\n"
        "- delete {strategy}: Delete a strategy from the database\n"
        "```"
}
